name: Deploy GH pages

on:
  push:
    branches: [ devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install
        npm run build
